spring:
  application:
    name: ai-powered-support-ticket-categorize

  datasource:
    url: jdbc:postgresql://localhost:5432/support_db
    username: postgres
    password: root$123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
#    openai:
#      api-key: your_openai_api_key_here
#      chat:
#        options:
#          model: gpt-4o-mini

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:3b
          temperature: 0.1

springdoc:
  packages-to-scan: ai.support.ticket.controller
  api-doc:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha